name: Run tests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Commit / Branch / Tag / SHA to checkout
        required: false
        default: ""
      python-version:
        description: Python version
        required: true
        default: "3.x"
  workflow_call:
    inputs:
      tag:
        description: Commit / Branch / Tag / SHA to checkout
        required: false
        default: ""
        type: string
      python-version:
        description: Python version
        required: true
        default: "3.x"
        type: string

permissions:
  contents: read

jobs:
  tests:
    uses: bagofseeds/actions/.github/workflows/test.yaml@main
    with:
      tag: ${{ inputs.tag }}
      python-version: ${{ inputs.python-version }}
